app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    
    path('', views.file_list, name='file_list'),
    path('download/', views.download_file, name='download_file'),
]

ya_disk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .services import YaDiskAPI



def file_list(request):
    """
    Отображает список файлов с Яндекс.Диска по публичному ключу.

    Args: request: HTTP запрос Django
    Returns: HttpResponse: Отрендеренный шаблон со списком файлов
    context:
        files (List): Список файлов с Яндекс.Диска
        public_key (str): Публичный ключ, введенный пользователем
    """

    public_key = request.GET.get('public_key', '')
    try:
        files = []
        if public_key:
            files = YaDiskAPI.get_file(public_key)

        context = {
            'files': files,
            'public_key': public_key,
        }

        return render(request, 'app/file_list.html', context)
    
    except Exception as e:
        return render(request, 'app/file_list.html', {'error': str(e)})


def download_file(request) -> HttpResponse:
    """
    Обрабатывает запрос на скачивание файла.
    Перенаправляет пользователя на прямую ссылку для скачивания.

    Args: request: HTTP запрос Django

    Returns:
        HttpResponseRedirect: Редирект на URL скачивания
        HttpResponse: Сообщение об ошибке при неверном запросе

    Query Parameters:
        public_key (str): Публичный ключ Яндекс.Диска
        path (str): Путь к файлу на Яндекс.Диске
    """

    public_key = request.GET.get("public_key", "")
    path = request.GET.get("path", "")

    try:
        if public_key and path:
            download_url = YaDiskAPI.download_file(public_key, path)
            return HttpResponseRedirect(download_url)
        
    except Exception as e:
        return render(request, 'app/file_list.html', {'error': str(e)})
    

app/templates/app/file_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yandex Disk</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="text-center mb-4">Поиск файлов на Yandex Disk</h1>
                
                {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ error }}
                </div>
                {% endif %}

                <div class="card shadow-sm">
                    <div class="card-body">
                        <form method="get" class="mb-4">
                            <div class="input-group">
                                <input type="text" class="form-control" name="public_key" 
                                       placeholder="Введите публичный ключ" value="{{ public_key }}" />
                                <button class="btn btn-primary" type="submit">Поиск</button>
                            </div>
                        </form>
    
                        {% if files %}
                            <ul class="list-group">
                                {% for file in files %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <div>
                                            {{ file.name }} 
                                            <span class="badge bg-secondary">{{ file.type }}</span>
                                        </div>
                                        <a href="{% url 'app:download_file' %}?public_key={{ public_key }}&path={{ file.path }}" 
                                           class="btn btn-outline-primary btn-sm">
                                            Скачать
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% elif public_key and not error %}
                            <div class="alert alert-info">Файлы не найдены</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>